general.import = [
"./him.toml",
"./keyboard.toml",
]

[window]
padding               = { x = 8, y = 8 }
opacity               = 1.0
blur                  = false
class                 = { instance = "Alacritty", general = "Alacritty" }

[font]
normal                = { family = "JetBrainsMono", style = "Bold" }
bold                  = { family = "JetBrainsMono", style = "Bold" }
italic                = { family = "JetBrainsMono", style = "Italic" }
bold_italic           = { family = "JetBrainsMono", style = "ExtraBold Italic" }
size                  = 12
offset                = { x = 0, y = 1 }
glyph_offset          = { x = 0, y = 1 }
builtin_box_drawing = false

[selection]
save_to_clipboard     = true

[cursor.style]
shape                 = "Block"
blinking              = "Never"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 1000
blink_timeout         = 0

[[hints.enabled]]
command = "firefox"
hyperlinks = true
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

