[[language]]
name = "c"
file-types  = ["c", "h"]
roots = [".ccls", "Makefile", "CMakeLists.txt"]
language-servers = ["cc-ls"]

[language-server.cc-ls]
command = "ccls"

[[language]]
name = "go"
roots = ["go.mod"]
language-servers = ["gopls"]
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "requirements.txt"]
language-servers = ["pylsp"]
formatter = { command = "yapf" }

[[language]]
name = "typst"
roots = ["typst.toml"]
language-servers = ["tinymist"]
auto-format = true
formatter = { command = "typstyle" }
